### ISSUE TITLE
python dependency

### ISSUE THREAD

**Issue by eviltik** [silverwind/cidr-tools#1]
Hi @silverwind !

Thank you for this module.

Suggestion 1: mention that this module need python to be installed on the system.
Suggestion 2: rewrite the python code into a js one 💃

**Comment by silverwind** [comment]
1. It's mentioned at the top of the readme, maybe not prominent enough
2. Very hard as there is nothing comparable to Python's `netaddr` in JS land, so I'd first have to create a general-purpose IP library that's up to the task.

**Comment by eviltik** [comment]
I was looking for a libs like your's, but finaly i've made something just to feet my needs here https://github.com/eviltik/cidr-clean. Features are not the same as yours.

https://github.com/rs/node-netmask under the wood, it should be interesting for your general-purpose IP lib perhaps

Cheers !

**Comment by silverwind** [comment]
Unfortunately, it has no IPv6 support, which I consider a must-have.

**Comment by eviltik** [comment]
absolutely :( 

https://github.com/rs/node-netmask/issues/8

**Comment by eviltik** [comment]
btw, this can help

* https://github.com/whitequark/ipaddr.js
* https://github.com/beaugunderson/ip-address

**Comment by silverwind** [comment]
I've started a rewrite in JS, it's not quite bug-free yet and a bit heavy on the dependencies, but should get there eventually.

**Comment by silverwind** [comment]
2.0.0 is out which is now pure Javascript.
