### ISSUE TITLE
How to use cidrTools with ES Module project

### ISSUE THREAD

**Issue by tyyzqmf** [silverwind/cidr-tools#16]
I import by `import cidrTools from 'cidr-tools';` and get `Error [ERR_REQUIRE_ESM]: require() of ES Module`

**Comment by silverwind** [comment]
Something in your toolchain must be transpiling your project to CJS, which can not load ESM. See this page for more info and possible solutions:

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
