### ISSUE TITLE
Can this be used to convert an IP range into a CIDR block?

### ISSUE THREAD

**Issue by jhuckaby** [silverwind/cidr-tools#18]
Please forgive the question.  I have read the docs, but I cannot see if this is possible with cidr-tools.  What I want is to start with something like as the input:

```
[ '217.146.182.0', '217.146.182.255' ]
```

And end up with this as the output:

```
'217.146.182/24'
```

Does cidr-tools have a function to perform this conversion, or am I barking up the wrong tree?

(If barking up the wrong tree, do you know of a module that can perform this kind of transformation?)

Thank you so much for your work.

**Comment by silverwind** [comment]
Currently there is no suitable exported function for this, but it may be possible to add the inverse of `parse`, e.g. `stringify`, where you would modify at least `start` and `end`:

```js
[Object: null prototype] {
  single: true,
  cidr: '1.1.1.0/32',
  version: 4,
  prefix: '32',
  start: 16843008n,
  end: 16843008n
}
```

**Comment by jhuckaby** [comment]
I totally understand.  Thank you for the reply!  I agree it doesn't really fit into your module's API.  Closing this issue now.  Have a great rest of your weekend!
