### ISSUE TITLE
#overlap - incorrect result

### ISSUE THREAD

**Issue by tomturton** [silverwind/cidr-tools#5]
`cidrTools.overlap('fe80:1:0:0:0:0:0:0', 'fe80::/10');`

expected: `true`
result: `false`

**Comment by tomturton** [comment]
This was 2.2.8, but seemed to only occur in the project I am working on, for some reason.

**Comment by silverwind** [comment]
Yep, returning `true` for me:

````js
> require(".").overlap('fe80:1:0:0:0:0:0:0', 'fe80::/10')
true
````

No idea, maybe you were on a older version after all?

**Comment by silverwind** [comment]
Added this example as a test case.

**Comment by tomturton** [comment]
I found out what had happened.

I had used Browserify to create a browser version of the this library, and other scripts.

In one project, the resulting libs.js file was indented, in the other project it was not.
The whitespace in the indented version essentially changed the cidr-regex!

Took a while to track down.

Great library, thanks.

**Comment by silverwind** [comment]
Very weird indeed. Might be that the script is ES6 which browserify might not be able to handle correctly. Would suggest using ES6-compatible minifier, for example [terser](https://github.com/terser-js/terser).
